Repository kolmafia/kolmafia, pull requests merged in 2021-11, with the labels that each got.

#162 Language Server - have Token extend Range
  build.gradle
  src/net/sourceforge/kolmafia/textui/Line.java
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/LineTest.java
  test/net/sourceforge/kolmafia/textui/ParserTest.java
  test/net/sourceforge/kolmafia/textui/ScriptData.java
Labels: language-server

#194 Language Server - Expose Location-related methods
  src/net/sourceforge/kolmafia/textui/Line.java
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/LineTest.java
  test/net/sourceforge/kolmafia/textui/ParserTest.java
Labels: language-server

#201 Language Server - split ParserTest
  test/net/sourceforge/kolmafia/textui/ParserTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/AggregateLiteralTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/AggregateTypeTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/AssignmentTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/BasicScopeTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/BasicScriptTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/CatchTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/CommentTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ConcatenateTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ConditionalTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/DirectiveTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/EscapeSequenceTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ExpressionTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ForEachLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ForLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionCallTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionInvocationTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionReturnTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/IncDecTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/JavaForLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/LoopBreakTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/LoopContinueTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/NumericValueTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/PluralValueTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/RecordTypeTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/RecordValueTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/RepeatUntilLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ScriptExitTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/SortByTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/StaticScopeTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/StringTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/SwitchTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/TemplateStringTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/TernaryExpressionTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/TryTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/TypeDefTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/TypedValueTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/UserDefinedFunctionTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/VariableReferenceTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/VariableTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/WhileLoopTest.java
Labels: language-server

#196 Language Server - expect aggregates when seeing {
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/AggregateLiteralTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/RecordValueTest.java
Labels: language-server

#208 Language Server - Locations - Variable
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/Variable.java
  test/net/sourceforge/kolmafia/textui/parsetree/ForEachLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ForLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/JavaForLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/VariableTest.java
Labels: language-server

#209 Language Server - Locations - Try
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/Try.java
  test/net/sourceforge/kolmafia/textui/parsetree/TryTest.java
Labels: language-server

#210 Language Server - Locations - Function
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/Function.java
  src/net/sourceforge/kolmafia/textui/parsetree/UserDefinedFunction.java
  test/net/sourceforge/kolmafia/textui/parsetree/UserDefinedFunctionTest.java
Labels: language-server

#211 Language Server - Locations - BasicScript
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/BasicScript.java
  test/net/sourceforge/kolmafia/textui/parsetree/BasicScriptTest.java
Labels: language-server

#213 Language Server - Locations - Operator
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/Assignment.java
  src/net/sourceforge/kolmafia/textui/parsetree/Operation.java
  src/net/sourceforge/kolmafia/textui/parsetree/Operator.java
  test/net/sourceforge/kolmafia/textui/parsetree/AssignmentTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ExpressionTest.java
Labels: language-server

#224 Language Server - Locations - Value (preparation)
  src/net/sourceforge/kolmafia/textui/parsetree/Value.java
Labels: language-server

#225 Language Server - Locations - Catch
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/Catch.java
  test/net/sourceforge/kolmafia/textui/parsetree/CatchTest.java
Labels: language-server

#226 Language Server - Locations - FunctionInvocation
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/FunctionCall.java
  src/net/sourceforge/kolmafia/textui/parsetree/FunctionInvocation.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionInvocationTest.java
Labels: language-server

#223 Language Server - Locations - Conditional
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/Conditional.java
  src/net/sourceforge/kolmafia/textui/parsetree/Else.java
  src/net/sourceforge/kolmafia/textui/parsetree/ElseIf.java
  src/net/sourceforge/kolmafia/textui/parsetree/If.java
  test/net/sourceforge/kolmafia/textui/parsetree/ConditionalTest.java
Labels: language-server

#239 Language Server - Locations - Implicit values
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/RecordInitializer.java
  test/net/sourceforge/kolmafia/textui/parsetree/ConditionalTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/JavaForLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/RecordValueTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/SwitchTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/VariableReferenceTest.java
Labels: language-server

#243 MenuItemList raw types
  src/net/sourceforge/kolmafia/swingui/menu/BookmarkMenu.java
  src/net/sourceforge/kolmafia/swingui/menu/MenuItemList.java
  src/net/sourceforge/kolmafia/swingui/menu/ScriptMenu.java
  src/net/sourceforge/kolmafia/swingui/menu/WindowMenu.java
Labels: raw-types

#246 SortedList raw types
  src/net/sourceforge/kolmafia/utilities/LockableListFactory.java
  src/net/sourceforge/kolmafia/utilities/SortedList.java
Labels: raw-types

#247 BuffRequestFrame raw types
  src/net/sourceforge/kolmafia/swingui/BuffRequestFrame.java
Labels: raw-types

#245 ClanManageFrame raw types
  src/net/sourceforge/kolmafia/request/ClanMembersRequest.java
  src/net/sourceforge/kolmafia/swingui/ClanManageFrame.java
Labels: raw-types

#248 A few other raw types
  src/net/sourceforge/kolmafia/request/ZapRequest.java
  src/net/sourceforge/kolmafia/swingui/SkillBuffFrame.java
  src/net/sourceforge/kolmafia/swingui/panel/GenericPanel.java
  src/net/sourceforge/kolmafia/swingui/panel/UseItemEnqueuePanel.java
  src/net/sourceforge/kolmafia/swingui/widget/TableCellFactory.java
Labels: raw-types

#49 Language Server - Locations - rest
  src/net/sourceforge/kolmafia/textui/Parser.java
  src/net/sourceforge/kolmafia/textui/parsetree/Assignment.java
  src/net/sourceforge/kolmafia/textui/parsetree/CompositeReference.java
  src/net/sourceforge/kolmafia/textui/parsetree/Concatenate.java
  src/net/sourceforge/kolmafia/textui/parsetree/Evaluable.java
  src/net/sourceforge/kolmafia/textui/parsetree/Expression.java
  src/net/sourceforge/kolmafia/textui/parsetree/FunctionCall.java
  src/net/sourceforge/kolmafia/textui/parsetree/If.java
  src/net/sourceforge/kolmafia/textui/parsetree/IncDec.java
  src/net/sourceforge/kolmafia/textui/parsetree/Operation.java
  src/net/sourceforge/kolmafia/textui/parsetree/TernaryExpression.java
  src/net/sourceforge/kolmafia/textui/parsetree/Value.java
  src/net/sourceforge/kolmafia/textui/parsetree/VariableReference.java
  test/net/sourceforge/kolmafia/textui/parsetree/AssignmentTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ExpressionTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/ForLoopTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionCallTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/IncDecTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/TemplateStringTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/TernaryExpressionTest.java
  test/net/sourceforge/kolmafia/textui/parsetree/VariableReferenceTest.java
Labels: language-server

#242 well_stocked
  src/net/sourceforge/kolmafia/textui/RuntimeLibrary.java
Labels: enhancement

#263 Update KoLmafiaCLI.java
  src/net/sourceforge/kolmafia/KoLmafiaCLI.java
Labels: security

#250 Language Server - error locations preparations
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/ParserTest.java
  test/net/sourceforge/kolmafia/textui/ScriptData.java
Labels: language-server

#266 Raw arrays - EquipmentManager
  src/net/sourceforge/kolmafia/request/EquipmentRequest.java
  src/net/sourceforge/kolmafia/session/EquipmentManager.java
  src/net/sourceforge/kolmafia/session/RabbitHoleManager.java
  src/net/sourceforge/kolmafia/swingui/GearChangeFrame.java
  src/net/sourceforge/kolmafia/swingui/panel/DailyDeedsPanel.java
  src/net/sourceforge/kolmafia/textui/command/HatterCommand.java
Labels: raw-types

#269 Language Server - error locations - RecordType
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/RecordTypeTest.java
Labels: language-server

#271 Language Server - error locations - WhileLoop
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/WhileLoopTest.java
Labels: language-server

#272 Language Server - error locations - RepeatUntilLoop
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/RepeatUntilLoopTest.java
Labels: language-server

#275 Language Server - error location - ForEachLoop
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/ForEachLoopTest.java
Labels: language-server

#273 Language Server - error locations - JavaForLoop
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/JavaForLoopTest.java
Labels: language-server

#276 Language Server - error locations - SortBy
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/SortByTest.java
Labels: language-server

#277 Language Server - error locations - LoopBreak
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/LoopBreakTest.java
Labels: language-server

#278 Language Server - error locations - LoopContinue
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/LoopContinueTest.java
Labels: language-server

#279 Language Server - error locations - Catch
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/CatchTest.java
Labels: language-server

#290 Language Server - error locations - AggregateType
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/AggregateTypeTest.java
Labels: language-server

#281 Language Server - error locations - Conditional
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/ConditionalTest.java
Labels: language-server

#280 Language Server - error locations - Try
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/TryTest.java
Labels: language-server

#288 Language Server - error locations - TypeDef
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/TypeDefTest.java
Labels: language-server

#287 Language Server - error locations - CompositeReference
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/VariableReferenceTest.java
Labels: language-server

#286 Language Server - error locations - FunctionCall
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionCallTest.java
Labels: language-server

#285 Language Server - error locations - Assignment
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/AssignmentTest.java
Labels: language-server

#284 Language Server - error locations - RecordValue
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/RecordValueTest.java
Labels: language-server

#283 Language Server - error locations - FunctionInvocation
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/FunctionInvocationTest.java
Labels: language-server

#282 Language Server - error locations - Switch
  src/net/sourceforge/kolmafia/textui/Parser.java
  test/net/sourceforge/kolmafia/textui/parsetree/SwitchTest.java
Labels: language-server
